version: "3.4"

networks:
  backend:
  web:

volumes:
  netflixprojectdotnetV2.postgres-database:

services:
  netflixProjectDotnetDB:
    container_name: postgres
    image: postgres:11.12
    volumes:
      - netflixprojectdotnetV2.postgres-database:/var/lib/postgresql/data
    env_file:
      - ./database.env
    ports:
      - "15432:5432"
    expose:
      - "15432"
    networks:
      - backend
      
  netflix-backend:
    container_name: netflix-backend
    build:
      context: ./netflixProjectBackendDotNet
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal;Port=15432;Database=netflixProjectDotNet;User Id=postgres;Password=admin;
      - Jwt__Issuer=issuer
      - Jwt__Key=hO1bl4Mr3SQkmIVD0kdEpaaA4zVC+g6xxdQwYt0MkNY=
    ports:
      - "5002:5002"
    depends_on:
      - netflixProjectDotnetDB
    networks:
      - backend
      - web
      
  netflix-frontend:
    build:
      context: ./netflixProjectFrontAngular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - netflix-backend
